### ISSUE TITLE
TypeError: Cannot read property 'toLowerCase' of undefined on ionic cordova build

### ISSUE THREAD

**Issue by rob-moore** [apache/cordova-ios#642]
# Bug Report

## Problem
As of July 8, 2019 we are no longer able to make buidls on azure dev ops. However we are still able to make builds using the same environments locally. None of our code has changed nor have we updated any packages regarding cordova / ionic / ionic-ios.

We are pretty locked into the versions of everything as well since many of our plugins rely on specific versions.

### What is expected to happen?
Our iOS builds work.

### What does actually happen?
Our iOS builds do not work.

## Information

Here's the error message: 

`2019-07-10T20:44:21.1877430Z Reading build config file:
2019-07-10T20:44:24.6080980Z Cannot read property 'toLowerCase' of undefined
2019-07-10T20:44:24.6081970Z TypeError: Cannot read property 'toLowerCase' of undefined
2019-07-10T20:44:24.6082730Z     at /Users/vsts/agent/2.153.2/work/r1/a/platforms/ios/cordova/lib/list-emulator-build-targets:54:45
2019-07-10T20:44:24.6083240Z     at Array.forEach (<anonymous>)
2019-07-10T20:44:24.6083790Z     at /Users/vsts/agent/2.153.2/work/r1/a/platforms/ios/cordova/lib/list-emulator-build-targets:52:44
2019-07-10T20:44:24.6084000Z     at Array.reduce (<anonymous>)
2019-07-10T20:44:24.6084570Z     at /Users/vsts/agent/2.153.2/work/r1/a/platforms/ios/cordova/lib/list-emulator-build-targets:50:57
2019-07-10T20:44:24.6084770Z     at Array.reduce (<anonymous>)
2019-07-10T20:44:24.6085350Z     at /Users/vsts/agent/2.153.2/work/r1/a/platforms/ios/cordova/lib/list-emulator-build-targets:45:28
2019-07-10T20:44:24.6085580Z     at _fulfilled (/Users/vsts/agent/2.153.2/work/r1/a/platforms/ios/cordova/node_modules/q/q.js:854:54)
2019-07-10T20:44:24.6085740Z     at /Users/vsts/agent/2.153.2/work/r1/a/platforms/ios/cordova/node_modules/q/q.js:883:30
2019-07-10T20:44:24.6086840Z     at Promise.promise.promiseDispatch (/Users/vsts/agent/2.153.2/work/r1/a/platforms/ios/cordova/node_modules/q/q.js:816:13)
2019-07-10T20:44:24.6265650Z [ERROR] An error occurred while running subprocess cordova.`

### Command or Code

`ionic cordova build ios --prod --release`

### Environment, Platform, Device

Azure dev ops hosted mac osx agent: 
`Xcode Version:
Xcode 10.0
Build version 10A255

-- OS X info ----------------------------------

    sw_vers
    ProductName: Mac OS X
    ProductVersion: 10.14.5
    BuildVersion: 18F132

    system_profiler SPSoftwareDataType
    Software:

    System Software Overview:

    System Version: macOS 10.14.5 (18F132)
    Kernel Version: Darwin 18.6.0
    Boot Volume: Macintosh HD
    Boot Mode: Normal
    User Name: vsts (vsts)
    Secure Virtual Memory: Enabled
    System Integrity Protection: Enabled

-- Disk 

    Total size: 407812136960 bytes (380Gi)
    Free: 170547421184 bytes (159Gi)

### Version information
Cordova: 8.1.2
Ionic: 3.9.2
Ionic-CLI: 1.3.12
OSX: 10.14.5
Xcode: 10.2.1

Cocoapods:
`2019-07-10T20:41:30.9691640Z Using FirebaseAnalytics (4.2.0)`
   `2019-07-10T20:41:30.9791730Z Using FirebaseCore (4.0.20)`
   `2019-07-10T20:41:30.9805710Z Using FirebaseInstanceID (2.0.10)`
  ` 2019-07-10T20:41:30.9831570Z Using FirebaseMessaging (2.0.8)`
   `2019-07-10T20:41:30.9899960Z Using GoogleToolboxForMac (2.2.1)`
   `2019-07-10T20:41:30.9923750Z Using Protobuf (3.8.0)`
   `2019-07-10T20:41:30.9931990Z Using nanopb (0.3.901)`

Cordova / ionic plugins:
`2019-07-10T20:33:19.9670070Z iOS project created with cordova-ios@4.5.5` `2019-07-10T20:33:20.3484870Z Discovered plugin "cordova-plugin-inappbrowser" in config.xml. Adding it to the project`
`2019-07-10T20:33:41.1322100Z Installing "cordova-plugin-inappbrowser" for ios`
   `2019-07-10T20:33:41.3054690Z Adding cordova-plugin-inappbrowser to package.json`
   `2019-07-10T20:33:41.3147790Z Saved plugin info for "cordova-plugin-inappbrowser" to config.xml`

   `2019-07-10T20:33:41.3198890Z Discovered plugin "cordova-sqlite-storage" in config.xml. Adding it to the project`
   `2019-07-10T20:34:01.6352970Z Installing "cordova-sqlite-storage" for ios`
   `2019-07-10T20:34:01.7410530Z installing external dependencies via npm`
   `2019-07-10T20:34:03.8214800Z npm install of external dependencies ok`
   `2019-07-10T20:34:03.8963600Z Adding cordova-sqlite-storage to package.json`
   `2019-07-10T20:34:03.9166350Z Saved plugin info for "cordova-sqlite-storage" to config.xml`
   `2019-07-10T20:34:03.9177620Z Discovered plugin "cordova-plugin-statusbar" in config.xml. Adding it to the project`
   `2019-07-10T20:34:24.1222160Z Installing "cordova-plugin-statusbar" for ios`
   `2019-07-10T20:34:24.2460940Z Adding cordova-plugin-statusbar to package.json`
   `2019-07-10T20:34:24.2528660Z Saved plugin info for "cordova-plugin-statusbar" to config.xml`
   `2019-07-10T20:34:24.2579060Z Discovered plugin "cordova-plugin-camera" in config.xml. Adding it to the project`
   `2019-07-10T20:34:44.8945870Z Installing "cordova-plugin-camera" for ios`
   `2019-07-10T20:34:45.0331550Z Adding cordova-plugin-camera to package.json`
   `2019-07-10T20:34:45.0404840Z Saved plugin info for "cordova-plugin-camera" to config.xml`
   `2019-07-10T20:34:45.0471320Z Discovered plugin "ionic-plugin-deeplinks" in config.xml. Adding it to the project`
   `2019-07-10T20:35:06.7945700Z Installing "ionic-plugin-deeplinks" for ios`
  ` 2019-07-10T20:35:07.0247640Z Adding ionic-plugin-deeplinks to package.json`
  `2019-07-10T20:35:07.0334500Z Saved plugin info for "ionic-plugin-deeplinks" to config.xml`
   `2019-07-10T20:35:07.0388660Z Discovered plugin "cordova-plugin-splashscreen" in config.xml. Adding it to the project`
   `2019-07-10T20:35:28.0101830Z Installing "cordova-plugin-splashscreen" for ios`
   `2019-07-10T20:35:28.1455420Z Adding cordova-plugin-splashscreen to package.json`
   `2019-07-10T20:35:28.1531470Z Saved plugin info for "cordova-plugin-splashscreen" to config.xml`
   `2019-07-10T20:35:28.1600270Z Discovered plugin "cordova-plugin-ionic" in config.xml. Adding it to the project`
   `2019-07-10T20:35:48.7180470Z Installing "cordova-plugin-ionic" for ios`
   `2019-07-10T20:35:48.8202010Z Plugin dependency "cordova-plugin-splashscreen@5.0.3" already fetched, using that version.`
`2019-07-10T20:35:48.8213610Z Dependent plugin "cordova-plugin-splashscreen" already installed on ios.`
`2019-07-10T20:35:49.6569300Z Adding cordova-plugin-ionic to package.json`
`2019-07-10T20:35:49.6570290Z Saved plugin info for "cordova-plugin-ionic" to config.xml`
`2019-07-10T20:35:49.6571070Z Discovered plugin "cordova-plugin-datepicker" in config.xml. Adding it to the project`
`2019-07-10T20:36:08.9927260Z Installing "cordova-plugin-datepicker" for ios`
`2019-07-10T20:36:09.1254480Z Adding cordova-plugin-datepicker to package.json`
`2019-07-10T20:36:09.1310480Z Saved plugin info for "cordova-plugin-datepicker" to config.xml`
`2019-07-10T20:36:09.1386000Z Discovered plugin "ionic-plugin-keyboard" in config.xml. Adding it to the project`
`2019-07-10T20:36:29.8743760Z Installing "ionic-plugin-keyboard" for ios`
`2019-07-10T20:36:29.8939500Z Adding ionic-plugin-keyboard to package.json`
`2019-07-10T20:36:29.8999920Z Saved plugin info for "ionic-plugin-keyboard" to config.xml`
`2019-07-10T20:36:29.9129060Z Discovered plugin "cordova-plugin-whitelist" in config.xml. Adding it to the project`
`2019-07-10T20:36:50.1476320Z Installing "cordova-plugin-whitelist" for ios`
`2019-07-10T20:36:50.2704360Z Adding cordova-plugin-whitelist to package.json`
`2019-07-10T20:36:50.2773230Z Saved plugin info for "cordova-plugin-whitelist" to config.xml`
`2019-07-10T20:36:50.2894940Z Discovered plugin "cordova-plugin-device" in config.xml. Adding it to the project`
`2019-07-10T20:37:10.9462820Z Installing "cordova-plugin-device" for ios`
`2019-07-10T20:37:11.0897820Z Adding cordova-plugin-device to package.json`
`2019-07-10T20:37:11.0967270Z Saved plugin info for "cordova-plugin-device" to config.xml`
`2019-07-10T20:37:11.1112300Z Discovered plugin "phonegap-plugin-push" in config.xml. Adding it to the project`
`2019-07-10T20:37:31.4835580Z Installing "phonegap-plugin-push" for ios`
`2019-07-10T20:38:03.6116300Z Adding phonegap-plugin-push to package.json`
`2019-07-10T20:38:03.6225990Z Saved plugin info for "phonegap-plugin-push" to config.xml`
`2019-07-10T20:38:03.6377380Z Discovered plugin "cordova-android-play-services-gradle-release" in config.xml. Adding it to the project`
`2019-07-10T20:38:24.3007310Z Installing "cordova-android-play-services-gradle-release" for ios`
`2019-07-10T20:38:24.4156610Z Adding cordova-android-play-services-gradle-release to package.json`
`2019-07-10T20:38:24.4211450Z Saved plugin info for "cordova-android-play-services-gradle-release" to config.xml`
`2019-07-10T20:38:24.4337920Z Discovered plugin "cordova-plugin-google-analytics" in config.xml. Adding it to the project`
`2019-07-10T20:38:46.5920780Z Installing "cordova-plugin-google-analytics" for ios`
`2019-07-10T20:38:46.8615340Z Adding cordova-plugin-google-analytics to package.json`
`2019-07-10T20:38:46.8663250Z Saved plugin info for "cordova-plugin-google-analytics" to config.xml`
`2019-07-10T20:38:46.8775160Z Discovered plugin "cordova-plugin-file" in config.xml. Adding it to the project`
`2019-07-10T20:39:07.7236000Z Installing "cordova-plugin-file" for ios`
`2019-07-10T20:39:07.8943270Z Adding cordova-plugin-file to package.json`
`2019-07-10T20:39:07.9003840Z Saved plugin info for "cordova-plugin-file" to config.xml`
`2019-07-10T20:39:07.9222460Z Discovered plugin "cordova-plugin-file-transfer" in config.xml. Adding it to the project`
`2019-07-10T20:39:27.9672940Z Installing "cordova-plugin-file-transfer" for ios`
`2019-07-10T20:39:28.0684910Z Plugin dependency "cordova-plugin-file@6.0.1" already fetched, using that version.`
`2019-07-10T20:39:28.0699710Z Dependent plugin "cordova-plugin-file" already installed on ios.`
`2019-07-10T20:39:28.0963310Z Adding cordova-plugin-file-transfer to package.json`
`2019-07-10T20:39:29.0947290Z Saved plugin info for "cordova-plugin-file-transfer" to config.xml`
`2019-07-10T20:39:29.0948380Z Discovered plugin "cordova-plugin-file-opener2" in config.xml. Adding it to the project`
`2019-07-10T20:39:47.9644200Z Installing "cordova-plugin-file-opener2" for ios`
`2019-07-10T20:39:48.1021890Z Adding cordova-plugin-file-opener2 to package.json`
`2019-07-10T20:39:48.1093730Z Saved plugin info for "cordova-plugin-file-opener2" to config.xml`
`2019-07-10T20:39:48.1261880Z Discovered plugin "cordova-plugin-ionic-webview" in config.xml. Adding it to the project`
`2019-07-10T20:40:07.8593130Z Installing "cordova-plugin-ionic-webview" for ios`
`2019-07-10T20:40:09.6977930Z Adding cordova-plugin-ionic-webview to package.json`
`2019-07-10T20:40:09.7032940Z Saved plugin info for "cordova-plugin-ionic-webview" to config.xml`
`2019-07-10T20:40:09.7156750Z Discovered plugin "cordova-plugin-network-information" in config.xml. Adding it to the project`
`2019-07-10T20:40:28.8271640Z Installing "cordova-plugin-network-information" for ios`
`2019-07-10T20:40:28.9659900Z Adding cordova-plugin-network-information to package.json`
`2019-07-10T20:40:28.9706380Z Saved plugin info for "cordova-plugin-network-information" to config.xml`
`2019-07-10T20:40:28.9874070Z Discovered plugin "phonegap-plugin-mobile-accessibility" in config.xml. Adding it to the project`
`2019-07-10T20:40:47.7028940Z Installing "phonegap-plugin-mobile-accessibility" for ios`
`2019-07-10T20:40:47.8063430Z Plugin dependency "cordova-plugin-device@1.1.7" already fetched, using that version.`
`2019-07-10T20:40:47.8073440Z Dependent plugin "cordova-plugin-device" already installed on ios.`
`2019-07-10T20:40:47.8079910Z Plugin dependency "cordova-plugin-network-information@2.0.1" already fetched, using that version.`
`2019-07-10T20:40:47.8098600Z Dependent plugin "cordova-plugin-network-information" already installed on ios.`
`2019-07-10T20:40:47.8386800Z Adding phonegap-plugin-mobile-accessibility to package.json`
`2019-07-10T20:40:47.8442130Z Saved plugin info for "phonegap-plugin-mobile-accessibility" to config.xml`

## Checklist

- [x] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by dpogue** [comment]
This is fixed in cordova-ios 5.0.0

**Comment by daviddickson** [comment]
I've run into this exact same issue. Updating cordova-ios did not fix the issue for me.

**Comment by brodybits** [comment]
In case of continued issues please raise a new issue with [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). It is fine to say “I think issue #642 is not fixed” in the new issue if the [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) can demonstrate that this issue is not really fixed.

We do not support closed issues.
