### ISSUE TITLE
Cocoapods 1.8.x platform add fails

### ISSUE THREAD

**Issue by kjng** [apache/cordova-ios#700]
# Bug Report

### What is expected to happen?

iOS platform is successfully added using Cocoapods 1.8.x and running `cordova platform add ios`

### What does actually happen?

An error is thrown from Cordova attempting to run pod install.

## Information

I am using cordova-plugin-firebasex which needs to install relevant pods.

The error message is:
> 'The CocoaPods repo has not been synced yet, this will take a long time (approximately 500MB as of Sept 2016). Please run `pod setup` first to sync the repo.'

It appears to originate from https://github.com/apache/cordova-ios/blob/f43812ab249a6fe7bca3ab2611de7d8a9dc080f2/bin/templates/scripts/cordova/lib/check_reqs.js#L132 and I think this is caused by changes in Cocoapods 1.8.x.

With Cocoapods 1.8.x, the master spec repo isn't required/included, so I think the check_reqs repo validation that Cordova does while trying to install pods fails.

### Command or Code

`cordova platform add ios`

### Environment, Platform, Device

I'm building using an Azure DevOps MacOS build agent:

MacOS 10.14
Cocoapods 1.8.3

### Version information

Cordova CLI: 9.0.0
cordova-ios: 5.0.1

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by DominicBoettger** [comment]
Same here. We solved it by downgrading cocoapods in our azure devops pipelines. Now our builds needs additional 10 minutes to be built :-( .

**Comment by erisu** [comment]
#719 should resolve this.

**Comment by mibzman** [comment]
This issue is only partially resolved.  #717 has the same behavior, except that it only occurs when the app name has a single quote.

**Comment by brodybits** [comment]
> This issue is only partially resolved. #717 has the same behavior
> [...]

Due to limited resources we do not like to support discussions in closed issues. Do you see anything beyond issue #717 that needs to be fixed regarding the platform failure on Cocoapods 1.8.x?

If so, it would really help the user community if you would raise a new issue with the required information including the standard [minimal, reproducible example ([1])](https://stackoverflow.com/help/minimal-reproducible-example).

[1] https://stackoverflow.com/help/minimal-reproducible-example
